# Generated by Django 5.2 on 2025-04-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_settings_logo_height_settings_logo_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handcraftimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='handcraftimage',
            name='image',
            field=models.ImageField(default='logos/default.jpg', upload_to='handcrafts/'),
            preserve_default=False,
        ),
    ]
