# Generated by Django 5.2 on 2025-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_handcraftimage_image_url_handcraftimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
    ]
