# Generated by Django 5.2 on 2025-04-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_settings_site_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='handcraftvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='handcraft_videos/'),
        ),
        migrations.AlterField(
            model_name='handcraftvideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
