# Generated by Django 5.2 on 2025-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_appointment_user_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
